### ISSUE TITLE
# of pellets and active pokes not the same 

### ISSUE THREAD

**Issue by kbarclay55** [KravitzLabDevices/FED3_library#5]

**Comment by KravitzLab** [comment]
Can you describe how to re-create this issue with FED3?

**Comment by KravitzLab** [comment]
The issue was due to timing and interrupts, such that a left poke could occur, and before the FED dispensed a pellet the mouse could poke his nose in the pellet well.  In this case, the left poke would be registered, but the pellet would not be, because the Feed() function would stop before it dropped a pellet and added 1 to the pellet count.  

I've sped a few things up in the library to reduce this possibility, but if there's a supermouse that can poke and then get to the pellet well at lightspeed they may still be able to cause this to happen.  I'll close this issue for now though, please try library version 1.0.6 and let me know if this issue is improved.
