### ISSUE TITLE
SetClock is bricking device?

### ISSUE THREAD

**Issue by dlhagger** [KravitzLabDevices/FED3_library#61]
After running SetClock from the examples menu in FED3 library, programs will not run after being re-flashed to the device. Device screen doesn't show anything, serial log is empty. I've done this to three different devices now, if I update without resetting the clock, everything works as normal?

Any thoughts?

**Comment by KravitzLab** [comment]
Hi - Flashing code (SetClock or other code) to a board cannot brick the device, something else is going on.  To track this down can you answer:

  1.  When you run SetClock does it flash correctly, showing the correct time/date on the screen?
  2.  After this are you flashing another FED3 library example or your own code?
  3.  If you re-flash SetClock to a non-reponsive device does it flash correctly again?


________________________________
From: David Haggerty ***@***.***>
Sent: Tuesday, November 1, 2022 1:50 PM
To: KravitzLabDevices/FED3_library ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KravitzLabDevices/FED3_library] SetClock is bricking device? (Issue #61)


* External Email - Caution *

After running SetClock from the examples menu in FED3 library, programs will not run after being re-flashed to the device. Device screen doesn't show anything, serial log is empty. I've done this to three different devices now, if I update without resetting the clock, everything works as normal?

Any thoughts?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKravitzLabDevices%2FFED3_library%2Fissues%2F61&data=05%7C01%7Calexxai%40wustl.edu%7Cac9f45679ff84c45f88108dabc39f1f9%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C638029254301210124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7SvC7WWTiRYrUafQvlb%2F74UMVn%2FAl%2BeTjZTm9zihexo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD76MGKRDNXNVSFEEXINXBTWGFQ7HANCNFSM6AAAAAARUKXYHA&data=05%7C01%7Calexxai%40wustl.edu%7Cac9f45679ff84c45f88108dabc39f1f9%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C638029254301210124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hRetzRVRiTVYJK%2FEoef3xRNR2BvF%2F1SQk1bjC%2FgSycE%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by dlhagger** [comment]
It will flash correctly and the screen will turn on to display the correct date and time. 

When I use an example sketch (FR1) it says the file is uploaded and verified correctly, but the device screen shows nothing and is non responsive. 

If I then reflash the set clock code it will successfully show the date and time again.

**Comment by KravitzLab** [comment]
Cool - it's not "bricked" if you can reflash code and it works.

It sounds like an old library version. That can cause incompatibilities with certain code, as a library can be used in the FR1 program and not SetClock.  Can you make sure all of your libraries are up to date and try again?  If you go to the Arduino Library Manager you can search for "Updatable" under the "Type" dropdown.  Update anything that needs it and see if that fixes it?


________________________________

**Comment by KravitzLab** [comment]
One other idea if updating libraries doesn't help - The set clock program does not call the SD card while all FED3 programs will.  I've seen weird things happen where SD cards can cause the Adalogger to hang when they're too full or have certain file types on them (like .pptx).  I think the SD library can take too long initializing in these cases and it can crash.  Can you try clearing out the SD card or trying a new one to see if that fixes it?

**Comment by dlhagger** [comment]
I tried updating all libraries and a fresh install of Arduino to make sure I wasn't messing anything up. Same issue. 

Wiped the SD card and also tried a new one, same issue. 

The only thing I noticed on re-install is that stepper.h wasn't included as a dependency for FED3 library and the FR1 code asked me to call it, so installed it from library manager, but still having the issue. 

If I double press the reset button to re-flash now, the far left neopixel's LED lights up solid green?

I've tried rolling the adafruit SAMD library all the way back to 1.5 as well, and nothing.

**Comment by KravitzLab** [comment]
That sounds really annoying! I'll have to replicate your issue here to figure out what's going on.

Can you go into the Arduino preferences and turn on "Verbose output", and then paste the Arduino IDE output during compile here? That will include all of the library versions your computer is using.  Can you also point me to the sketch you're trying to flash onto the FED3?

In the meantime, can you also try again from a different computer?

________________________________

**Comment by dlhagger** [comment]
I was able to fix by rolling back to the legacy Arduino IDE, if anyone else has issues using the new IDE 2.0.1 - please note that for some reason, at least in my hands, I was having issues with flashing code correctly to the boards.
