### ISSUE TITLE
Failure to compile with 1.7.0, problem with FED3WAN.h

### ISSUE THREAD

**Issue by Francois7D** [KravitzLabDevices/FED3_library#64]
When I try to compile a program with this library version, we get the following error

fatal error: SoftwareSerial.h: No such file or directory

Is there any easy fix ? 

Thanks !

**Comment by KravitzLab** [comment]
Hi!  The Software Serial library you are missing is [here](https://github.com/mcci-catena/SoftwareSerial).  

However, I would advise using the latest stable release (available from the Arduino Library Manager) instead of this one.  This is an update that is not complete yet so likely won't be useful to you beyond the stable release.
